version: '3.8'

services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-react-app
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro