-- Add missing translations for policy and accessibility pages and common back button (fixed quotes)
-- Common
INSERT INTO public.translations (component, category, key, he, en) VALUES 
('Common', 'common', 'common.back', 'חזרה', 'Back')
ON CONFLICT (key) DO UPDATE SET component = EXCLUDED.component, category = EXCLUDED.category, he = EXCLUDED.he, en = EXCLUDED.en;

-- Privacy Policy
INSERT INTO public.translations (component, category, key, he, en) VALUES 
('PrivacyPolicy','privacy','privacyPolicy.title','מדיניות פרטיות','Privacy Policy'),
('PrivacyPolicy','privacy','privacyPolicy.intro.title','מבוא','Introduction'),
('PrivacyPolicy','privacy','privacyPolicy.intro.content','אנו מכבדים את פרטיותך ומתחייבים להגן על המידע האישי שלך. מסמך זה מסביר אילו נתונים אנו אוספים, כיצד אנו משתמשים בהם וכיצד אנו שומרים עליהם.','We respect your privacy and are committed to protecting your personal information. This document explains what data we collect, how we use it, and how we keep it safe.'),
('PrivacyPolicy','privacy','privacyPolicy.dataCollection.title','איסוף מידע','Data Collection'),
('PrivacyPolicy','privacy','privacyPolicy.dataCollection.description','אנו עשויים לאסוף את הנתונים הבאים בעת שימושך באתר ובשירותים שלנו:','We may collect the following data when you use our website and services:'),
('PrivacyPolicy','privacy','privacyPolicy.dataCollection.items.personal','פרטים אישיים שאתה מוסר מרצונך (שם, טלפון, אימייל).','Personal details you provide (name, phone, email).'),
('PrivacyPolicy','privacy','privacyPolicy.dataCollection.items.usage','נתוני שימוש ותנועה באתר לשיפור חוויית המשתמש.','Usage and traffic data to improve user experience.'),
('PrivacyPolicy','privacy','privacyPolicy.dataCollection.items.contact','תיעוד פניות ושיחות שירות לצורך טיפול ושיפור השירות.','Records of inquiries and support for service and quality.'),
('PrivacyPolicy','privacy','privacyPolicy.dataUse.title','שימוש במידע','How We Use Data'),
('PrivacyPolicy','privacy','privacyPolicy.dataUse.description','אנו משתמשים במידע כדי לספק את השירות, לשפרו, ולשמור על קשר עמך.','We use your information to deliver the service, improve it, and stay in contact with you.'),
('PrivacyPolicy','privacy','privacyPolicy.dataUse.items.orders','ניהול הזמנות ותיאומים.','Managing orders and bookings.'),
('PrivacyPolicy','privacy','privacyPolicy.dataUse.items.service','שיפור השירות והתכנים באתר.','Improving the service and site content.'),
('PrivacyPolicy','privacy','privacyPolicy.dataUse.items.contact','מענה לפניות ותמיכה.','Responding to inquiries and support.'),
('PrivacyPolicy','privacy','privacyPolicy.dataUse.items.updates','שליחת עדכונים רלוונטיים בהסכמתך.','Sending relevant updates with your consent.'),
('PrivacyPolicy','privacy','privacyPolicy.dataSharing.title','שיתוף מידע','Data Sharing'),
('PrivacyPolicy','privacy','privacyPolicy.dataSharing.content','איננו משתפים מידע אישי עם צד שלישי אלא אם נדרש על פי חוק או לצורך מתן השירות (כגון ספקי תשתית), ובכפוף להתחייבויות סודיות.','We do not share personal information with third parties except as required by law or to provide the service (e.g., infrastructure providers) under confidentiality obligations.'),
('PrivacyPolicy','privacy','privacyPolicy.userRights.title','זכויותיך','Your Rights'),
('PrivacyPolicy','privacy','privacyPolicy.userRights.description','באפשרותך לבקש גישה, תיקון או מחיקה של המידע, וכן להתנגד לעיבוד מסוים.','You may request access, correction, or deletion of your data and object to certain processing.'),
('PrivacyPolicy','privacy','privacyPolicy.userRights.items.access','זכות לקבל עותק מהמידע שלך.','Right to obtain a copy of your data.'),
('PrivacyPolicy','privacy','privacyPolicy.userRights.items.correction','זכות לבקש תיקון מידע שגוי.','Right to request correction of inaccurate data.'),
('PrivacyPolicy','privacy','privacyPolicy.userRights.items.deletion','זכות לבקש מחיקה במקרים המתאימים.','Right to request deletion where applicable.'),
('PrivacyPolicy','privacy','privacyPolicy.userRights.items.objection','זכות להתנגד לעיבוד ישיר לצורכי שיווק.','Right to object to direct marketing.'),
('PrivacyPolicy','privacy','privacyPolicy.contact.title','יצירת קשר בנושא פרטיות','Privacy Contact'),
('PrivacyPolicy','privacy','privacyPolicy.contact.content','לכל שאלה בנושא פרטיות, ניתן לפנות אלינו בטלפון או במייל ונשמח לסייע.','For any privacy questions, contact us by phone or email and we’ll be happy to assist.'),
('PrivacyPolicy','privacy','privacyPolicy.lastUpdated','עודכן לאחרונה: אוגוסט 2025','Last updated: August 2025')
ON CONFLICT (key) DO UPDATE SET component = EXCLUDED.component, category = EXCLUDED.category, he = EXCLUDED.he, en = EXCLUDED.en;

-- Terms of Use
INSERT INTO public.translations (component, category, key, he, en) VALUES 
('TermsOfUse','legal','termsOfUse.title','תנאי שימוש','Terms of Use'),
('TermsOfUse','legal','termsOfUse.general.title','כללי','General'),
('TermsOfUse','legal','termsOfUse.general.content','השימוש באתר כפוף לתנאים אלה. השימוש מהווה הסכמה לתנאים.','Use of the website is subject to these terms. By using the site you agree to them.'),
('TermsOfUse','legal','termsOfUse.bookings.title','הזמנות','Bookings'),
('TermsOfUse','legal','termsOfUse.bookings.description','תהליך ההזמנה נעשה בתיאום מראש ובכפוף לאישור.','Bookings are coordinated in advance and subject to confirmation.'),
('TermsOfUse','legal','termsOfUse.bookings.items.confirmation','ההזמנה מאושרת רק לאחר קבלת אישור מאיתנו.','A booking is confirmed only after our explicit confirmation.'),
('TermsOfUse','legal','termsOfUse.bookings.items.advance','ייתכן ונבקש מקדמה לשמירת התאריך.','An advance payment may be required to secure the date.'),
('TermsOfUse','legal','termsOfUse.bookings.items.payment','התשלום יוסדר במועד האירוע או לפי סיכום.','Payment is settled on the event date or as agreed.'),
('TermsOfUse','legal','termsOfUse.bookings.items.minimum','ייתכנו דרישות מינימום להזמנה.','Minimum order requirements may apply.'),
('TermsOfUse','legal','termsOfUse.pricing.title','מחירים ותשלומים','Pricing and Payments'),
('TermsOfUse','legal','termsOfUse.pricing.description','המחירים עשויים להשתנות ויכולים לכלול מע"מ בהתאם לחוק.','Prices may change and may include VAT where applicable.'),
('TermsOfUse','legal','termsOfUse.pricing.items.vat','המחירים כוללים/אינם כוללים מע"מ כפי שמצוין בהצעה.','Prices include/exclude VAT as specified in the offer.'),
('TermsOfUse','legal','termsOfUse.pricing.items.variable','המחיר הסופי תלוי בגודל האירוע ובדרישות מיוחדות.','Final price depends on event size and special requirements.'),
('TermsOfUse','legal','termsOfUse.pricing.items.payment','אמצעי תשלום מקובלים לפי סיכום.','Accepted payment methods as agreed.'),
('TermsOfUse','legal','termsOfUse.pricing.items.cancellation','מדיניות ביטול בהתאם למדיניות הביטולים.','Cancellation policy per our cancellation policy.'),
('TermsOfUse','legal','termsOfUse.conduct.title','התנהלות במקום','Conduct'),
('TermsOfUse','legal','termsOfUse.conduct.description','אנו מצפים להתנהלות מכבדת ושמירה על המקום.','We expect respectful conduct and care of the venue.'),
('TermsOfUse','legal','termsOfUse.conduct.items.smoking','אין לעשן באזורים אסורים.','No smoking in restricted areas.'),
('TermsOfUse','legal','termsOfUse.conduct.items.outside','אסור להכניס מזון/שתייה מבחוץ ללא אישור.','No outside food or drinks without approval.'),
('TermsOfUse','legal','termsOfUse.conduct.items.cleanliness','יש להקפיד על ניקיון וסדר.','Please maintain cleanliness and order.'),
('TermsOfUse','legal','termsOfUse.conduct.items.damage','נזק לרכוש יחויב בהתאם.','Damages to property will be charged accordingly.'),
('TermsOfUse','legal','termsOfUse.conduct.items.respect','יש לנהוג בכבוד כלפי צוות ואורחים.','Treat staff and guests with respect.'),
('TermsOfUse','legal','termsOfUse.liability.title','הגבלת אחריות','Limitation of Liability'),
('TermsOfUse','legal','termsOfUse.liability.content','איננו אחראים לנזקים עקיפים, תקלות טכניות או אירועים שאינם בשליטתנו.','We are not liable for indirect damages, technical issues, or events beyond our control.'),
('TermsOfUse','legal','termsOfUse.changes.title','שינויים בתנאים','Changes'),
('TermsOfUse','legal','termsOfUse.changes.content','אנו רשאים לעדכן תנאים אלו מעת לעת. העדכון ייכנס לתוקף עם פרסומו באתר.','We may update these terms from time to time. Updates take effect upon publication.'),
('TermsOfUse','legal','termsOfUse.contact.title','יצירת קשר','Contact'),
('TermsOfUse','legal','termsOfUse.contact.content','לשאלות בנוגע לתנאים, פנו אלינו בטלפון או במייל.','For questions about these terms, contact us by phone or email.'),
('TermsOfUse','legal','termsOfUse.lastUpdated','עודכן לאחרונה: אוגוסט 2025','Last updated: August 2025')
ON CONFLICT (key) DO UPDATE SET component = EXCLUDED.component, category = EXCLUDED.category, he = EXCLUDED.he, en = EXCLUDED.en;

-- Cancellation Policy
INSERT INTO public.translations (component, category, key, he, en) VALUES 
('CancellationPolicy','legal','cancellationPolicy.title','מדיניות ביטולים','Cancellation Policy'),
('CancellationPolicy','legal','cancellationPolicy.importantNotice.title','חשוב לדעת','Important'),
('CancellationPolicy','legal','cancellationPolicy.importantNotice.content','מדיניות הביטולים חלה על כל ההזמנות ונתונה לשיקול דעתנו בהתאם לנסיבות.','The cancellation policy applies to all bookings and may vary at our discretion based on circumstances.'),
('CancellationPolicy','legal','cancellationPolicy.times.title','זמני ביטול','Cancellation Timeframes'),
('CancellationPolicy','legal','cancellationPolicy.times.upTo24.title','עד 24 שעות לפני האירוע','Up to 24 hours before the event'),
('CancellationPolicy','legal','cancellationPolicy.times.upTo24.items.free','ביטול ללא עלות.','Cancellation with no charge.'),
('CancellationPolicy','legal','cancellationPolicy.times.upTo24.items.refund','החזר מלא למקדמה ששולמה.','Full refund of any advance payment.'),
('CancellationPolicy','legal','cancellationPolicy.times.upTo24.items.noCharge','לא ייגבה תשלום.','No charges will be applied.'),
('CancellationPolicy','legal','cancellationPolicy.times.12to24.title','בין 12 ל-24 שעות','12–24 hours before'),
('CancellationPolicy','legal','cancellationPolicy.times.12to24.items.charge50','יחויב 50% מעלות ההזמנה.','50% of the order value will be charged.'),
('CancellationPolicy','legal','cancellationPolicy.times.12to24.items.refund50','החזר 50% מהמקדמה אם שולמה.','50% refund of the advance, if paid.'),
('CancellationPolicy','legal','cancellationPolicy.times.12to24.items.preparationCost','כיסוי עלויות הכנה ובזבוזים.','Covers preparation and wastage costs.'),
('CancellationPolicy','legal','cancellationPolicy.times.under12.title','פחות מ-12 שעות','Under 12 hours'),
('CancellationPolicy','legal','cancellationPolicy.times.under12.items.fullCharge','יחויב מלוא הסכום.','Full amount will be charged.'),
('CancellationPolicy','legal','cancellationPolicy.times.under12.items.noRefund','אין החזר למקדמה.','No refund of the advance.'),
('CancellationPolicy','legal','cancellationPolicy.times.under12.items.reschedule','ניתן לבחון דחייה למועד אחר לפי זמינות.','Rescheduling may be offered subject to availability.'),
('CancellationPolicy','legal','cancellationPolicy.specialCases.title','מקרים מיוחדים','Special Cases'),
('CancellationPolicy','legal','cancellationPolicy.specialCases.forceMajeure.title','כוח עליון','Force Majeure'),
('CancellationPolicy','legal','cancellationPolicy.specialCases.forceMajeure.content','במקרה של כוח עליון תטופל ההזמנה בגמישות מרבית.','In force majeure events, we will handle the booking with maximum flexibility.'),
('CancellationPolicy','legal','cancellationPolicy.specialCases.medical.title','מקרה רפואי','Medical Case'),
('CancellationPolicy','legal','cancellationPolicy.specialCases.medical.content','עם הצגת אישור רפואי ייתכנו הקלות או דחייה.','With medical proof, relief or rescheduling may be offered.'),
('CancellationPolicy','legal','cancellationPolicy.process.title','תהליך ביטול','Cancellation Process'),
('CancellationPolicy','legal','cancellationPolicy.process.steps.call','צרו קשר טלפוני לבקשת הביטול.','Call us to submit your cancellation request.'),
('CancellationPolicy','legal','cancellationPolicy.process.steps.details','מסרו פרטי הזמנה ומועד האירוע.','Provide booking details and event date.'),
('CancellationPolicy','legal','cancellationPolicy.process.steps.confirmation','קבלו אישור ביטול מסודר.','Receive a formal cancellation confirmation.'),
('CancellationPolicy','legal','cancellationPolicy.process.steps.refund','החזר כספי יבוצע בתוך מספר ימי עסקים.','Refunds are processed within a few business days.'),
('CancellationPolicy','legal','cancellationPolicy.modifications.title','שינויים בהזמנה','Modifications'),
('CancellationPolicy','legal','cancellationPolicy.modifications.description','ניתן לבקש שינוי פרטים במקום ביטול, בכפוף לזמינות.','You may request changes instead of cancellation, subject to availability.'),
('CancellationPolicy','legal','cancellationPolicy.modifications.items.upTo24','שינויים עד 24 שעות ללא עלות.','Changes up to 24 hours at no cost.'),
('CancellationPolicy','legal','cancellationPolicy.modifications.items.under24','פחות מ-24 שעות – ייתכן חיוב חלקי.','Under 24 hours – partial fees may apply.'),
('CancellationPolicy','legal','cancellationPolicy.modifications.items.availability','כל שינוי כפוף לזמינות והתאמות לוגיסטיות.','All changes depend on availability and logistics.'),
('CancellationPolicy','legal','cancellationPolicy.contact.title','יצירת קשר לביטולים','Contact for Cancellations'),
('CancellationPolicy','legal','cancellationPolicy.contact.forCancellations','לביטולים ועדכונים, נשמח לעמוד לשירותכם.','For cancellations and updates, we are here to help.'),
('CancellationPolicy','legal','cancellationPolicy.contact.phone','טלפון: 052-0000000','Phone: +972-52-000-0000'),
('CancellationPolicy','legal','cancellationPolicy.contact.email','אימייל: info@example.com','Email: info@example.com'),
('CancellationPolicy','legal','cancellationPolicy.contact.hours','שעות מענה: א'' - ה'' 9:00–18:00','Support hours: Sun–Thu 9:00–18:00'),
('CancellationPolicy','legal','cancellationPolicy.lastUpdated','עודכן לאחרונה: אוגוסט 2025','Last updated: August 2025')
ON CONFLICT (key) DO UPDATE SET component = EXCLUDED.component, category = EXCLUDED.category, he = EXCLUDED.he, en = EXCLUDED.en;

-- Accessibility
INSERT INTO public.translations (component, category, key, he, en) VALUES 
('Accessibility','accessibility','accessibility.title','נגישות','Accessibility'),
('Accessibility','accessibility','accessibility.intro.content','אנו מחויבים להנגשת האתר והשירות לכלל המשתמשים, כולל אנשים עם מוגבלויות.','We are committed to making our website and services accessible to all users, including people with disabilities.'),
('Accessibility','accessibility','accessibility.visual.title','נגישות חזותית','Visual Accessibility'),
('Accessibility','accessibility','accessibility.visual.description','צבעים בניגוד גבוה, טקסטים ברורים והתאמת גודל כתב.','High-contrast colors, clear typography, and adjustable text sizes.'),
('Accessibility','accessibility','accessibility.auditory.title','נגישות שמיעתית','Auditory Accessibility'),
('Accessibility','accessibility','accessibility.auditory.description','תמלול לסרטונים ותוכן שאינו תלוי שמע.','Captions for videos and non-audio dependent content.'),
('Accessibility','accessibility','accessibility.motor.title','נגישות מוטורית','Motor Accessibility'),
('Accessibility','accessibility','accessibility.motor.description','ניווט מקלדת ותמיכה בקיצורי דרך.','Keyboard navigation and shortcut support.'),
('Accessibility','accessibility','accessibility.webFeatures.title','תכונות נגישות באתר','Web Accessibility Features'),
('Accessibility','accessibility','accessibility.webFeatures.items.keyboard','תמיכה מלאה בניווט באמצעות מקלדת.','Full keyboard navigation support.'),
('Accessibility','accessibility','accessibility.webFeatures.items.altText','טקסט אלטרנטיבי לכל התמונות.','Alt text for all images.'),
('Accessibility','accessibility','accessibility.webFeatures.items.contrast','יחסי ניגוד תקינים.','Proper contrast ratios.'),
('Accessibility','accessibility','accessibility.webFeatures.items.headings','מבני כותרות סמנטיים.','Semantic heading structure.'),
('Accessibility','accessibility','accessibility.webFeatures.items.links','קישורים ברורים עם תיאורים משמעותיים.','Clear links with meaningful descriptions.'),
('Accessibility','accessibility','accessibility.webFeatures.items.focus','מצב פוקוס מובחן וגלוי.','Visible, distinct focus states.'),
('Accessibility','accessibility','accessibility.webFeatures.items.screenReader','תמיכה בקוראי מסך.','Screen reader support.'),
('Accessibility','accessibility','accessibility.webFeatures.items.skipLink','קישור דילוג לתוכן העיקרי.','Skip to main content link.'),
('Accessibility','accessibility','accessibility.physicalFeatures.title','נגישות פיזית','Physical Accessibility'),
('Accessibility','accessibility','accessibility.physicalFeatures.description','במיקום העסק קיימות תשתיות נגישות בהתאם ליכולת.','Our physical location includes accessibility features where possible.'),
('Accessibility','accessibility','accessibility.physicalFeatures.items.wheelchair','גישה לכיסאות גלגלים (ככל שניתן).','Wheelchair access (where possible).'),
('Accessibility','accessibility','accessibility.physicalFeatures.items.restrooms','שירותים נגישים (במידת האפשר).','Accessible restrooms (where available).'),
('Accessibility','accessibility','accessibility.physicalFeatures.items.parking','חניות נגישות בקרבת המקום.','Accessible parking nearby.'),
('Accessibility','accessibility','accessibility.physicalFeatures.items.lighting','תאורה מתאימה ונעימה.','Suitable and comfortable lighting.'),
('Accessibility','accessibility','accessibility.physicalFeatures.items.staff','צוות מודע ומסייע.','Aware and helpful staff.'),
('Accessibility','accessibility','accessibility.continuousImprovement.title','שיפור מתמיד','Continuous Improvement'),
('Accessibility','accessibility','accessibility.continuousImprovement.content','אנו פועלים לשיפור תמידי ומזמינים משוב.','We continuously improve and welcome feedback.'),
('Accessibility','accessibility','accessibility.feedback.title','משוב על נגישות','Accessibility Feedback'),
('Accessibility','accessibility','accessibility.feedback.question','נתקלתם בקושי? נשמח לדעת.','Encountered an issue? Let us know.'),
('Accessibility','accessibility','accessibility.feedback.contact','צרו קשר ואנו נטפל בהקדם.','Contact us and we will handle it promptly.'),
('Accessibility','accessibility','accessibility.feedback.phone','טלפון: 052-0000000','Phone: +972-52-000-0000'),
('Accessibility','accessibility','accessibility.feedback.email','אימייל: info@example.com','Email: info@example.com'),
('Accessibility','accessibility','accessibility.feedback.response','נחזור אליכם בתוך מספר ימי עסקים.','We will respond within a few business days.'),
('Accessibility','accessibility','accessibility.additionalInfo.title','מידע נוסף','Additional Information'),
('Accessibility','accessibility','accessibility.additionalInfo.content','תיעוד והצהרות נגישות זמינים על פי דרישה.','Documentation and statements of accessibility are available on request.'),
('Accessibility','accessibility','accessibility.lastUpdated','עודכן לאחרונה: אוגוסט 2025','Last updated: August 2025')
ON CONFLICT (key) DO UPDATE SET component = EXCLUDED.component, category = EXCLUDED.category, he = EXCLUDED.he, en = EXCLUDED.en;