-- Add remaining booking translations
INSERT INTO public.translations (key, he, en, category) VALUES
('bookingSection.badge', '📅 הזמנה מקוונת', '📅 Online Booking', 'booking'),
('bookingSection.description', 'בחרו את התאריך והזמן המועדפים עליכם', 'Choose your preferred date and time', 'booking'),
('bookingSection.formTitle', 'בחירת תאריך וזמן', 'Select Date and Time', 'booking'),
('bookingSection.fields.date', 'תאריך', 'Date', 'booking'),
('bookingSection.fields.time', 'שעת התחלה', 'Start Time', 'booking'),
('bookingSection.fields.duration', 'משך הזמן', 'Duration', 'booking'),
('bookingSection.fields.guests', 'מספר אנשים', 'Number of People', 'booking'),
('bookingSection.placeholders.selectDate', 'בחרו תאריך', 'Select Date', 'booking'),
('bookingSection.placeholders.selectTime', 'בחרו שעה', 'Select Time', 'booking'),
('bookingSection.placeholders.noTimes', 'אין שעות זמינות', 'No available times', 'booking'),
('bookingSection.placeholders.selectDateFirst', 'בחרו תאריך תחילה', 'Select date first', 'booking'),
('bookingSection.placeholders.selectDuration', 'בחרו משך זמן', 'Select Duration', 'booking'),
('bookingSection.placeholders.howMany', 'כמה אנשים?', 'How many people?', 'booking'),
('bookingSection.placeholders.fullName', 'הכניסו את שמכם', 'Enter your name', 'booking'),
('bookingSection.placeholders.phone', '05X-XXXXXXX', '05X-XXXXXXX', 'booking'),
('bookingSection.durations.oneHour', 'שעה אחת', '1 Hour', 'booking'),
('bookingSection.durations.twoHours', 'שעתיים', '2 Hours', 'booking'),
('bookingSection.durations.threeHours', 'שלוש שעות', '3 Hours', 'booking'),
('bookingSection.durations.fourHours', 'ארבע שעות', '4 Hours', 'booking'),
('bookingSection.businessHours', 'שעות פתיחה:', 'Opening hours:', 'booking'),
('bookingSection.roomRecommendation', 'אנחנו נמצא עבורכם את החדר הטוב ביותר בהתאם לזמינות', 'We will find you the best room according to availability', 'booking'),
('bookingSection.summary.title', 'סיכום הזמנה', 'Booking Summary', 'booking'),
('bookingSection.summary.date', 'תאריך', 'Date', 'booking'),
('bookingSection.summary.time', 'שעה', 'Time', 'booking'),
('bookingSection.summary.duration', 'משך זמן', 'Duration', 'booking'),
('bookingSection.summary.guests', 'מספר אנשים', 'Number of People', 'booking'),
('bookingSection.summary.estimatedPrice', 'מחיר משוער', 'Estimated Price', 'booking'),
('bookingSection.summary.people', 'אנשים', 'people', 'booking'),
('bookingSection.checkAvailability.button', 'בדקו זמינות', 'Check Availability', 'booking'),
('bookingSection.available.title', 'מצוין! יש מקום פנוי', 'Great! Space is available', 'booking'),
('bookingSection.available.subtitle', 'מצאנו עבורכם את החדר הטוב ביותר', 'We found you the best room', 'booking'),
('bookingSection.notAvailable.title', 'מצטערים, אין חדרים פנויים', 'Sorry, no rooms available', 'booking'),
('bookingSection.notAvailable.description', 'בתאריך ובשעה שבחרתם אין חדרים זמינים.\nאנא בחרו אחת מהאפשרויות הבאות:', 'No rooms are available at your selected date and time.\nPlease choose one of the following options:', 'booking'),
('bookingSection.notAvailable.leaveMessage', 'השאירו הודעה', 'Leave a Message', 'booking'),
('bookingSection.notAvailable.callUs', 'התקשרו אלינו', 'Call Us', 'booking'),
('bookingSection.notAvailable.searchOther', 'חפשו זמנים אחרים', 'Search Other Times', 'booking'),
('bookingSection.notAvailable.contactForm.title', 'השאירו פרטים ונחזור אליכם', 'Leave details and we will get back to you', 'booking'),
('bookingSection.notAvailable.contactForm.send', 'שלחו הודעה', 'Send Message', 'booking'),
('bookingSection.notAvailable.hours', 'שעות פעילות מוקד: ראשון-חמישי 09:00-22:00 | שישי 09:00-15:00', 'Call center hours: Sunday-Thursday 09:00-22:00 | Friday 09:00-15:00', 'booking'),
('bookingSection.confirmBooking', 'אישור והזמנה', 'Confirm Booking', 'booking'),
('bookingSection.features.instant', 'אישור מיידי', 'Instant Confirmation', 'booking'),
('bookingSection.features.freeCancellation', 'ביטול חינם עד 24 שעות', 'Free cancellation up to 24 hours', 'booking'),
('bookingSection.features.securePayment', 'תשלום מאובטח', 'Secure Payment', 'booking'),
('bookingSection.features.support', 'תמיכה 24/7', '24/7 Support', 'booking')

ON CONFLICT (key) DO UPDATE SET 
  he = EXCLUDED.he,
  en = EXCLUDED.en,
  category = EXCLUDED.category,
  updated_at = now();