-- Add dynamic content translations
INSERT INTO public.translations (key, he, en, category) VALUES
-- Promotion items (dynamic content)
('promotions.items.birthday.title', 'חבילת יום הולדת מושלמת', 'Perfect Birthday Package', 'promotions'),
('promotions.items.birthday.description', 'חגיגה בלתי נשכחת עם חבילת יום הולדת מיוחדת הכוללת הכל', 'Unforgettable celebration with a special birthday package that includes everything', 'promotions'),
('promotions.items.birthday.validity', 'עד סוף החודש', 'Until end of month', 'promotions'),
('promotions.items.birthday.guestRange', 'עד 8 אנשים', 'Up to 8 people', 'promotions'),
('promotions.items.birthday.duration', '3 שעות', '3 hours', 'promotions'),
('promotions.items.birthday.feature1', 'חדר פרימיום מעוצב', 'Premium designed room', 'promotions'),
('promotions.items.birthday.feature2', 'עוגת יום הולדת מתנה', 'Birthday cake as gift', 'promotions'),
('promotions.items.birthday.feature3', 'משקאות קלים ללא הגבלה', 'Unlimited soft drinks', 'promotions'),
('promotions.items.birthday.feature4', 'תפריט חטיפים מיוחד', 'Special snacks menu', 'promotions'),
('promotions.items.birthday.feature5', 'קישוטי יום הולדת', 'Birthday decorations', 'promotions'),
('promotions.items.birthday.feature6', 'צילום מקצועי (30 דק'')', 'Professional photography (30 min)', 'promotions'),

('promotions.items.weekend.title', 'מבצע וויקאנד מטורף', 'Crazy Weekend Deal', 'promotions'),
('promotions.items.weekend.description', 'בסופי השבוע תיהנו ממחירים מיוחדים על כל החדרים', 'Enjoy special prices on all rooms during weekends', 'promotions'),
('promotions.items.weekend.validity', 'חמישי-שבת בלבד', 'Thursday-Saturday only', 'promotions'),
('promotions.items.weekend.guestRange', '2-6 אנשים', '2-6 people', 'promotions'),
('promotions.items.weekend.duration', '2 שעות', '2 hours', 'promotions'),
('promotions.items.weekend.feature1', 'כל החדרים במחיר מיוחד', 'All rooms at special price', 'promotions'),
('promotions.items.weekend.feature2', '2 משקאות אלכוהוליים', '2 alcoholic drinks', 'promotions'),
('promotions.items.weekend.feature3', 'צ''ייסרים ללא הגבלה', 'Unlimited chasers', 'promotions'),
('promotions.items.weekend.feature4', 'חטיפים מלוחים', 'Salty snacks', 'promotions'),
('promotions.items.weekend.feature5', 'שירותי DJ בתיאום מראש', 'DJ services with advance coordination', 'promotions'),

('promotions.items.group.title', 'חבילת קבוצת חברים', 'Friends Group Package', 'promotions'),
('promotions.items.group.description', 'מושלם לקבוצות גדולות - כל מה שצריך לערב מדהים', 'Perfect for large groups - everything needed for an amazing evening', 'promotions'),
('promotions.items.group.validity', 'זמין כל השבוע', 'Available all week', 'promotions'),
('promotions.items.group.guestRange', '10-15 אנשים', '10-15 people', 'promotions'),
('promotions.items.group.duration', '4 שעות', '4 hours', 'promotions'),
('promotions.items.group.feature1', 'חדר הדיאמונד הגדול', 'The large Diamond room', 'promotions'),
('promotions.items.group.feature2', 'בר מלא עם ברמן', 'Full bar with bartender', 'promotions'),
('promotions.items.group.feature3', 'מגוון חטיפים ומזמרות', 'Variety of snacks and nibbles', 'promotions'),
('promotions.items.group.feature4', 'מערכת קול מקצועית', 'Professional sound system', 'promotions'),
('promotions.items.group.feature5', 'תאורת דיסקו', 'Disco lighting', 'promotions'),
('promotions.items.group.feature6', 'שולחן ביליארד', 'Pool table', 'promotions'),

('promotions.items.happyhour.title', 'מבצע שעות השמחה', 'Happy Hours Deal', 'promotions'),
('promotions.items.happyhour.description', 'בין 14:00-18:00 תיהנו ממחירים מיוחדים במיוחד', 'Between 14:00-18:00 enjoy especially special prices', 'promotions'),
('promotions.items.happyhour.validity', 'ימים א''-ה'' בלבד', 'Sunday-Thursday only', 'promotions'),
('promotions.items.happyhour.guestRange', '2-8 אנשים', '2-8 people', 'promotions'),
('promotions.items.happyhour.duration', '2 שעות', '2 hours', 'promotions'),
('promotions.items.happyhour.feature1', 'כל החדרים זמינים', 'All rooms available', 'promotions'),
('promotions.items.happyhour.feature2', 'משקה בירה ראשון חינם', 'First beer drink free', 'promotions'),
('promotions.items.happyhour.feature3', 'חטיפים בסיסיים', 'Basic snacks', 'promotions'),
('promotions.items.happyhour.feature4', 'מוזיקה ללא הגבלה', 'Unlimited music', 'promotions'),
('promotions.items.happyhour.feature5', 'אפשרות להארכה במחיר מיוחד', 'Extension option at special price', 'promotions'),

-- Terms and conditions
('promotions.terms.item1', 'כל המבצעים בתוקף בכפוף לזמינות', 'All promotions valid subject to availability', 'promotions'),
('promotions.terms.item2', 'יש להזמין מראש ולאשר את המבצע', 'Must book in advance and confirm the promotion', 'promotions'),
('promotions.terms.item3', 'לא ניתן לשלב מבצעים', 'Cannot combine promotions', 'promotions'),
('promotions.terms.item4', 'תשלום מראש נדרש לאישור ההזמנה', 'Advance payment required to confirm booking', 'promotions'),
('promotions.terms.item5', 'ביטול עד 24 שעות מראש ללא תשלום', 'Cancellation up to 24 hours in advance free of charge', 'promotions'),
('promotions.terms.item6', 'המחירים כוללים מע"מ', 'Prices include VAT', 'promotions'),

-- Booking section translations
('booking.title', 'בחירת תאריך וזמן', 'Select Date and Time', 'booking'),
('booking.subtitle', 'בחרו את התאריך והזמן המועדפים עליכם', 'Choose your preferred date and time', 'booking'),
('booking.dateLabel', 'תאריך', 'Date', 'booking'),
('booking.timeLabel', 'שעה', 'Time', 'booking'),
('booking.durationLabel', 'משך זמן', 'Duration', 'booking'),
('booking.guestsLabel', 'מספר אורחים', 'Number of Guests', 'booking'),
('booking.checkAvailability', 'בדיקת זמינות', 'Check Availability', 'booking'),
('booking.available', 'זמין!', 'Available!', 'booking'),
('booking.notAvailable', 'לא זמין בזמן זה', 'Not available at this time', 'booking'),
('booking.roomSuggestion', 'החדר המומלץ עבורכם:', 'Recommended room for you:', 'booking'),
('booking.estimatedPrice', 'מחיר משוער:', 'Estimated price:', 'booking'),
('booking.contact.title', 'פרטי קשר לאישור הזמנה', 'Contact Details for Booking Confirmation', 'booking'),
('booking.contact.name', 'שם מלא', 'Full Name', 'booking'),
('booking.contact.phone', 'מספר טלפון', 'Phone Number', 'booking'),
('booking.bookingConfirmed', 'הזמנה אושרה!', 'Booking Confirmed!', 'booking'),
('booking.confirmationMessage', 'תודה! פרטי ההזמנה נשלחו אליכם בהודעה. נחזור אליכם בהקדם לאישור סופי.', 'Thank you! Booking details have been sent to you via message. We will get back to you soon for final confirmation.', 'booking')

ON CONFLICT (key) DO UPDATE SET 
  he = EXCLUDED.he,
  en = EXCLUDED.en,
  category = EXCLUDED.category,
  updated_at = now();