// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzxuamejtmrndjbdpfjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6eHVhbWVqdG1ybmRqYmRwZmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODI4MDEsImV4cCI6MjA3MDE1ODgwMX0.Zauiu_I5vBQAdTW4wRu8piC263-jfSe7rwczpea8BzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});